#!/usr/bin/env python3
"""Install the supplied SEO and Branding skills as project skills, adapted.

The archive holds 44 general consulting skills. Most assume a client engagement
on a CMS with an e-commerce funnel: they open by interrogating you for a brief
("What platform?", "Do you have GSC?") and then gate on approval. None of that
fits here — this is a static site generated by tools/build.py from a fixed
corpus, and the answers to every brief question are already known.

So each applicable skill is installed with the brief pre-filled from this
repository, the interrogation gates removed, and the generic advice bound to
the files that would actually change. The skills that only make sense for a
shop, a local business or a personal brand are not installed at all.

    python3 tools/install_skills.py <path-to-unzipped-archive>
"""
from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEST = ROOT / ".claude" / "skills"

# Applicable here, and why. Everything else in the archive is for a shop, a
# local business, a personal brand or a social migration, and is skipped.
KEEP = {
    "SEO & Search/technical-seo-checklist": "crawlability, indexation, CWV, structured data",
    "SEO & Search/seo-audit": "on-page analysis across the 65 generated pages",
    "SEO & Search/meta-tag-optimizer": "titles and descriptions, generated in build.py",
    "SEO & Search/schema-markup-guide": "JSON-LD for the school, its courses and its texts",
    "SEO & Search/site-architecture-plan": "URL structure and internal linking",
    "SEO & Search/featured-snippet-optimizer": "the corpora answer definitional queries well",
    "SEO & Search/youtube-seo": "468 embedded recordings across the site",
    "Branding & Design/brand-identity-guide": "documenting the design system that now exists",
    "Branding & Design/style-tile": "the visual direction, already implemented",
    "Branding & Design/color-palette-generator": "the pigment palette and its contrast budget",
    "Branding & Design/brand-voice-guide": "the English chrome the build writes",
    "Branding & Design/brand-audit": "consistency across 65 pages and two themes",
    "Branding & Design/visual-identity-brief": "briefing any future design work",
    "Branding & Design/icon-set-brief": "the inline SVG icon set",
}

PROJECT_CONTEXT = """
## Project context — the brief is already answered

This skill is installed inside the **samskrtam.info** repository. Do not ask the
brief questions below; they are answered here. Do not stop at a GATE for
approval unless the user has asked to review something specific.

| Brief input | Answer for this project |
|---|---|
| Site | https://samskrtam.info — Svarvāṇī Prakāśa · Sevā Nikuñjam, a Sanskrit pāṭhaśālā run by Usha Rani Sanka |
| Platform / CMS | None. A static site generated by `tools/build.py` from `src/data/*.json` into `dist/` |
| Page count | 65 generated pages |
| Audience | Students reading Sanskrit in the original — Rāmāyaṇa, Mahābhārata, the śāstras. Mostly India, Telugu- and Hindi-speaking, plus English readers |
| Languages | Sanskrit (Devanāgarī), Telugu, English/IAST — all three on the same pages |
| Analytics / GSC | None connected. No keyword-volume tool is available; do not invent search volumes |
| Commercial goal | None. No shop, no funnel, no lead capture. Donations go directly by UPI |
| Existing design system | `src/assets/css/site.css` — "The Illuminated Scriptorium": parchment, soot ink, saffron, brass, emerald, crimson, jamun. Nothing is a pill; colour is rubric, rule and tint; Indic is never tracked or uppercased |
| Existing brand assets | The haṃsa-over-book seal (`dist/assets/img/logo.png`), the motto संस्कृतं स्वधर्मस्य मूलम्, and three Indic typefaces the school already licensed |

### Where changes actually land

| To change | Edit |
|---|---|
| Any HTML, meta tag, or JSON-LD | `tools/build.py` — never `dist/` directly, it is generated |
| Colour, type, spacing, components | `src/assets/css/site.css` |
| Behaviour | `src/assets/js/site.js`, `src/assets/js/lipi.js` |
| Content | `src/data/*.json`, re-extracted from `original-site/` by `tools/extract.py` |

### Rules that override anything in this skill

1. **The school's own words are never rewritten.** Sanskrit, Telugu and the
   school's English prose are content, not copy. Only the chrome the build
   itself writes — leads, blurbs, button labels, empty states — is yours.
2. **Never invent a fact to fill a template.** No fabricated review counts,
   ratings, search volumes, prices, addresses, opening hours or UPI IDs. If a
   field has no truthful value, leave the field out.
3. **Run `python3 tools/audit.py` after any change.** It checks the built site
   against the mirror in `original-site/`; content parity is not negotiable.
4. Deliverables belong in `docs/`, not in `dist/`.

---
"""

GATE = re.compile(r"^\*\*GATE:.*$", re.M)


def adapt(text: str, slug: str) -> str:
    """Insert the project brief after the frontmatter, drop the approval gates."""
    m = re.match(r"^---\n.*?\n---\n", text, re.S)
    if not m:
        return PROJECT_CONTEXT + text
    front, body = m.group(0), text[m.end():]

    # the description should say this is bound to the project
    front = re.sub(
        r'(^description:\s*"?)(.*?)("?)$',
        lambda x: f'{x.group(1)}{x.group(2).rstrip(".")} — adapted for the samskrtam.info static site.{x.group(3)}',
        front, count=1, flags=re.M)

    # these skills only ever read and write files here
    if "allowed-tools:" in front:
        front = re.sub(r"^allowed-tools:.*$", "allowed-tools: Read Write Edit Glob Grep Bash",
                       front, count=1, flags=re.M)

    body = GATE.sub("_(No gate: the brief above is already settled — keep going.)_", body)

    # first heading, then the project context, then the rest
    parts = body.split("\n", 1)
    head = parts[0] if parts[0].startswith("#") else ""
    rest = parts[1] if head else body
    return front + (head + "\n" if head else "") + PROJECT_CONTEXT + rest


def main() -> None:
    if len(sys.argv) < 2:
        sys.exit(f"usage: {sys.argv[0]} <path-to-unzipped-archive>")
    src = Path(sys.argv[1])
    if not src.exists():
        sys.exit(f"not found: {src}")

    DEST.mkdir(parents=True, exist_ok=True)
    installed, skipped = [], []
    for rel, why in KEEP.items():
        f = src / rel / "SKILL.md"
        if not f.exists():
            skipped.append(rel)
            continue
        slug = rel.split("/")[-1]
        out = DEST / slug
        out.mkdir(parents=True, exist_ok=True)
        (out / "SKILL.md").write_text(adapt(f.read_text("utf-8"), slug), "utf-8")
        installed.append((slug, why))

    print(f"installed {len(installed)} skills into {DEST.relative_to(ROOT)}/\n")
    for slug, why in installed:
        print(f"  {slug:28s} {why}")
    if skipped:
        print("\nnot found in the archive:", ", ".join(skipped))

    everything = {p.parent.name for p in src.rglob("SKILL.md") if "__MACOSX" not in str(p)}
    left = sorted(everything - {s for s, _ in installed})
    print(f"\nnot installed ({len(left)} — for a shop, a local business, a personal brand, "
          f"or a social migration; none apply to a pāṭhaśālā's text library):")
    print("  " + ", ".join(left))


if __name__ == "__main__":
    main()
